apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-chart
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/subhdhal/helm.git
    targetRevision: HEAD
    path: demo-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
